language: node_js
node_js:
  - '10'
  - '9'
install:
  - npm install -g codecov
jobs:
  include:
    - stage: test
      script: npm t
    - stage: generate
      # This will ensure that the latest installed `codecov` is ran
      # each time
      script: codecov
notifications:
  email: false
