language: node_js
node_js:
  - '10'
  - '9'
# This causes Travis to error out for some reason
# See: https://github.com/travis-ci/travis-ci/issues/10113
# cache:
#   directories:
#     - 'node_modules'
notifications:
  email: false
