version: 2.1
orbs:
  # Always fetch the latest version of the orb
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in the orb
      - cypress/run
